version: "3.8"
services:
  postgres:
    image: postgres:15.2-alpine
    network_mode: bridge
    container_name: postgresDocker

    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=docker

  demmo:
    build:
      context: .
      target: service
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - postgres
    network_mode: bridge
    environment:
      DB_URL: 'jdbc:postgresql://127.0.0.1:5432/docker'
      DB_USER: 'docker'
      DB_PASSWORD: 'docker'
    working_dir: /app
    command:
      - java
      - -jar
      - demo-1.0.0.jar



volumes:
  postgres-data:
