version: "3.8"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres

    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=postgres

  demmo:
    build:
      context: .
      target: service
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - postgres
    environment:
      DB_URL: 'jdbc:postgresql://postgres:5432/postgres'
      DB_USER: 'docker'
      DB_PASSWORD: 'docker'
    working_dir: /app
    command:
      - java
      - -jar
      - demo-1.0.0.jar



volumes:
  postgres-data:
